version: '2'

services:
  proxy:
    image: traefik
    command: --docker --docker.domain=docker.localhost --logLevel=INFO
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
  web:
    image: cdssnc/ircc_frontend
    ports:
      - 3000
    build:
      context: ./web
      dockerfile: Dockerfile
    labels:
      - "traefik.backend=ircc_frontend"
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.port=3000"
  api:
    environment:
      - API_TOKEN
      - API_HOST
      - STORE_ID
    image: cdssnc/ircc_backend
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3001
    labels:
      - "traefik.backend=ircc_backend"
      - "traefik.frontend.rule=PathPrefix:/graphql"
      - "traefik.port=3001"

